version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: employee_mysql
    environment:
      MYSQL_ROOT_PASSWORD: userpassword
      MYSQL_DATABASE: employeedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

